---
title: "Boletim Fiscal dos Municípios Cearenses"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    logo: img/logo_ipece.png
    orientation: columns
    vertical_layout: fill
    theme:
      bootswatch: lumen
      bg: "#FFFFFF"
      fg: "#000000" 
      warning: "#f5903b"
      primary: "#111384"
      secondary: "#E9ECEF"
      success: "#73A839"
      info: "#033C73"
      base_font: !expr bslib::font_google("Prompt")
      code_font: !expr bslib::font_google("JetBrains Mono")
---

<script>
$('.navbar-logo').wrap('<a href="https://www.ipece.ce.gov.br/" target=_blank>');
</script>

<style>
.active {
  font-size:14px;
}
</style>


```{css}
.value-box {
  height: 80px;
  width: 120px;
  margin: 0 0 11px 0;
  white-space: nowrap;
  padding: 0px;
}

```



```{r setup, include = FALSE}

knitr::opts_chunk$set(
  cache = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.path = "figs/",
  cache.path = "_cache/",
  fig.process = function(x) {
    x2 <- sub("-\\d+([.][a-z]+)$", "\\1", x)
    if (file.rename(x, x2)) x2 else x
  }
)
```

```{r loadlibaries, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(clock)
library(shiny)
library(scales)
library(DT)
library(plotly)

#bslib::bs_themer()

thematic::thematic_rmd(
  font = "auto",
  # To get the dark bg on the geom_raster()
  sequential = thematic::sequential_gradient(fg_low = FALSE, fg_weight = 0, bg_weight = 1)
)

theme_set(theme_bw(base_size = 12))

```

```{r data}

indicadores <- read_rds(
  here::here('out/indicadores/indicadores_mun_ce.rds')
)


balancete_uf <- readr::read_rds(
    here::here(
    "out/dados_consolidados/balancetes/quadrimestral/balancete_uf_quadrimestral.rds"
  )
)

balancete_mun <- readr::read_rds(
    here::here(
    "out/dados_consolidados/balancetes/quadrimestral/balancete_mun_quadrimestral.rds"
  )
)

tamanho_fonte <- "font-size: 14px;"

```

Estado do Ceará
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

### Parâmetros

```{r parametros_uf}

nome_mun <- indicadores %>% 
  count(mun)

ano <- indicadores %>% 
  count(ano)

quadrimestre <- indicadores %>% 
  count(quadrimestre)

sliderInput("contact_rate", "Set contact rate", value = 5, min = 0, max = 30)

selectInput('indicador_fiscal', 'Indicadores Fiscais', names(indicadores)[7:11])

selectInput('ano', 'Ano', ano$ano, selected = '2021')

selectInput('quad', 'Quadrimestre', quadrimestre$quadrimestre)


```


Column {data-width=650}
-----------------------------------------------------------------------

### Balancete do Estado do Ceará

```{r table_ce, cache=FALSE}

renderTable({
  
    data_atual <- clock::date_build(
    year = as.numeric(input$ano),
    month = case_when(
      input$quad == "1" ~ 4,
      input$quad == "2" ~ 8,
      input$quad == "3" ~ 12
    )
  )

  data_defasada <- clock::add_months(data_atual, -12)

  variacao_uf <- balancete_uf %>%
    filter(
      date %in% c(data_atual, data_defasada)
    ) %>%
    group_by(conta) %>%
    mutate(
      variacao = (valor / lag(valor)) - 1
    ) %>% 
    ungroup() %>% 
    drop_na(variacao) %>% 
    select(conta, variacao)
  
    balancete_uf %>%
    filter(
      date %in% c(data_atual, data_defasada)
    ) %>%
    mutate(
      date = format(date, 'p%Y%m'),
      quadrimestre = as.character(quadrimestre)
      ) %>%
    select(conta, date, valor) %>%
    pivot_wider(
      names_from = date, 
      values_from = valor
      ) %>%
    left_join(variacao_uf, by = 'conta') %>%
    mutate(
      variacao = scales::percent(
        variacao, 
        accuracy = 0.01,
        big.mark = '.', 
        decimal.mark = ',')
    ) %>% 
    mutate(
      across(
        !c(conta, variacao), 
        ~scales::comma(., prefix = 'R$ ', big.mark = '.', decimal.mark = ','))
      ) %>% 
    rename(Conta = conta, 'Var.%' = variacao) 
  
})

```

Column {data-width=350}
-----------------------------------------------------------------------

### Período Corrente

```{r plot_1, cache=FALSE}

plotly::renderPlotly({
  
  g_indicadores <- indicadores %>% 
  filter(ano == input$ano, quadrimestre == input$quad) %>% 
  ggplot(aes_string(x = input$indicador_fiscal)) +
  geom_histogram(bins = 5)
  
  plotly::ggplotly(g_indicadores)
  
})


```

### Mesmo Período do Ano Anterior

```{r plot_2, cache=FALSE}

plotly::renderPlotly({
  
  g_indicadores2 <- indicadores %>% 
  filter(ano == input$ano, quadrimestre == input$quad) %>% 
  ggplot(aes_string(x = input$indicador_fiscal)) +
  geom_histogram(bins = 5)
  
  plotly::ggplotly(g_indicadores2)
  
})

```

Municípios Cearenses
=======================================================================


Column {.sidebar} 
-----------------------------------------------------------------------

### Parâmetros

```{r parametros}

nome_mun <- indicadores %>% 
  count(mun)

ano <- indicadores %>% 
  count(ano)

quadrimestre <- indicadores %>% 
  count(quadrimestre)

selectInput('indicador_fiscal_mun', 'Indicadores Fiscais', names(indicadores)[7:11])

selectInput('mun', 'Municípios Cearenses', nome_mun$mun, selected = 'Fortaleza')

selectInput('ano_mun', 'Ano', ano$ano, selected = '2021')

selectInput('quad_mun', 'Quadrimestre', quadrimestre$quadrimestre)

```

Column {data-width=70}
-----------------------------------------------------------------------


### Indep. Fiscal {.value-box}

```{r indic1, cache=FALSE}

renderValueBox({
  ind_fical <- indicadores %>%
    filter(
      ano == input$ano_mun,
      quadrimestre == input$quad_mun,
      mun == input$mun
    ) %>%
    select("independecia_fiscal") %>%
    pull()

  ind_fical_pc <- scales::percent(
    ind_fical,
    accuracy = 0.01,
    big.mark = ".",
    decimal.mark = ","
  )

  valueBox(
    value = tags$p(ind_fical_pc, style = tamanho_fonte),
    #icon = "fa-area-chart",
    color = if (ind_fical >= 0) "primary" else "warning"
  )
})


```


### Custeio {.value-box}

```{r indic2, cache=FALSE}

renderValueBox({
  ind_fical <- indicadores %>%
    filter(
      ano == input$ano_mun,
      quadrimestre == input$quad_mun,
      mun == input$mun
    ) %>%
    select("custeio_total") %>%
    pull()


  ind_fical_pc <- scales::percent(
    ind_fical,
    accuracy = 0.01,
    big.mark = ".",
    decimal.mark = ","
  )

  valueBox(
    value = tags$p(ind_fical_pc, style = tamanho_fonte),
    #icon = "fa-area-chart",
    color = if (ind_fical >= 0) "primary" else "warning"
  )
})

```


### Invest. {.value-box}

```{r indic3, cache=FALSE}

renderValueBox({
  ind_fical <- indicadores %>%
    filter(
      ano == input$ano_mun,
      quadrimestre == input$quad_mun,
      mun == input$mun
    ) %>%
    select("investimentos_rec_prop") %>%
    pull()

  ind_fical_pc <- scales::percent(
    ind_fical,
    accuracy = 0.01,
    big.mark = ".",
    decimal.mark = ","
  )

  valueBox(
    value = tags$p(ind_fical_pc, style = tamanho_fonte),
    #icon = "fa-area-chart",
    color = if (ind_fical >= 0) "primary" else "warning"
  )
})


```

### Ser.Div./RCL {.value-box}

```{r indic4, cache=FALSE}

renderValueBox({
  ind_fical <- indicadores %>%
    filter(
      ano == input$ano_mun,
      quadrimestre == input$quad_mun,
      mun == input$mun
    ) %>%
    select("servico_divida_rcl") %>%
    pull()

  ind_fical_pc <- scales::percent(
    ind_fical,
    accuracy = 0.01,
    big.mark = ".",
    decimal.mark = ","
  )

  valueBox(
    value = tags$p(ind_fical_pc, style = tamanho_fonte),
    #icon = "fa-area-chart",
    color = if (ind_fical >= 0) "primary" else "warning"
  )
})


```

### Desp. Pessoal {.value-box}

```{r indic5, cache=FALSE}

renderValueBox({
  ind_fical <- indicadores %>%
    filter(
      ano == input$ano_mun,
      quadrimestre == input$quad_mun,
      mun == input$mun
    ) %>%
    select("desp_pessoal") %>%
    pull()

  ind_fical_pc <- scales::percent(
    ind_fical,
    accuracy = 0.01,
    big.mark = ".",
    decimal.mark = ","
  )

  valueBox(
    value = tags$p(ind_fical_pc, style = tamanho_fonte),
    #icon = "fa-area-chart",
    color = if (ind_fical >= 0) "primary" else "warning"
  )
})


```


### DCL/RCL {.value-box}

```{r indic6, cache=FALSE}

renderValueBox({
  ind_fical <- indicadores %>%
    filter(
      ano == input$ano_mun,
      quadrimestre == input$quad_mun,
      mun == input$mun
    ) %>%
    select("dcl_rcl") %>%
    pull()

  ind_fical_pc <- scales::percent(
    ind_fical,
    accuracy = 0.01,
    big.mark = ".",
    decimal.mark = ","
  )

  valueBox(
    value = tags$p(ind_fical_pc, style = tamanho_fonte),
    #icon = "fa-area-chart",
    color = if (ind_fical >= 0) "primary" else "warning"
  )
})


```


Column {data-width=650}
-----------------------------------------------------------------------

### Balancete dos Municípios Cearenses

```{r table_mun, cache=FALSE}

renderTable({
  data_atual <- clock::date_build(
    year = as.numeric(input$ano_mun),
    month = case_when(
      input$quad_mun == "1" ~ 4,
      input$quad_mun == "2" ~ 8,
      input$quad_mun == "3" ~ 12
    )
  )

  data_defasada <- clock::add_months(data_atual, -12)

  variacao_mun <- balancete_mun %>%
    filter(
      date %in% c(data_atual, data_defasada),
      mun == input$mun
    ) %>%
    group_by(conta) %>%
    mutate(
      variacao = (valor / lag(valor)) - 1
    ) %>% 
    ungroup() %>% 
    drop_na(variacao) %>% 
    select(conta, variacao)
    

  balancete_mun %>%
    filter(
      date %in% c(data_atual, data_defasada),
      mun == input$mun
    ) %>%
    mutate(
      date = format(date, 'p%Y%m'),
      quadrimestre = as.character(quadrimestre)
      ) %>%
    select(conta, date, valor) %>%
    pivot_wider(
      names_from = date, 
      values_from = valor
      ) %>%
    left_join(variacao_mun, by = 'conta') %>%
    mutate(
      variacao = scales::percent(
        variacao, 
        accuracy = 0.01,
        big.mark = '.', 
        decimal.mark = ',')
    ) %>% 
    mutate(
      across(
        !c(conta, variacao), 
        ~scales::comma(., prefix = 'R$ ', big.mark = '.', decimal.mark = ','))
      ) %>% 
    rename(Conta = conta, 'Var.%' = variacao) 
})

```

Column {data-width=320}
-----------------------------------------------------------------------

### Período Corrente

```{r plot_mun_1, cache=FALSE}

plotly::renderPlotly({
  
  g1 <- indicadores %>% 
  filter(ano == input$ano, quadrimestre == input$quad) %>% 
  ggplot(aes_string(x = input$indicador_fiscal_mun)) +
  geom_histogram(bins = 5)
  
  grafico1 <- plotly::ggplotly(g1)
  
  grafico1
  

  
})

```

### Mesmo Período do Ano Anterior

```{r plot_mun_2, cache=FALSE}


renderPlotly(
  {
    g2 <- indicadores %>% 
        filter(ano == input$ano_mun, quadrimestre == input$quad_mun) %>% 
        ggplot(aes_string(x = input$indicador_fiscal_mun)) +
        geom_histogram(bins = 5)
    
    grafico2 <- plotly::ggplotly(g2)
    
    grafico2
    
  }
)




```


Indicadores
=======================================================================

```{r indicaores_download}

DT::datatable(
  indicadores %>% select(-ano, -quadrimestre, -mes),
  extensions = "Buttons",
  options = list(
    dom = "Bfrtip",
    buttons = c("copy", "csv", "excel", "print", "pdf")
  ),
  rownames = FALSE
)

```

Balancetes Municipais
=======================================================================

```{r balancetes_download}

DT::datatable(
  balancete_mun %>%
    select(-mes) %>%
    mutate(
      valor = scales::comma(valor, accuracy = 0.01, big.mark = ".", decimal.mark = ","),
      ano = as.factor(ano),
      quadrimestre = as.factor(quadrimestre)
    ),
  extensions = "Buttons",
  options = list(
    dom = "Bfrtip",
    buttons = c("copy", "csv", "excel", "print", "pdf")
  ),
  rownames = FALSE,
  filter = list(
    position = "top", clear = FALSE
  )
)

```



